export type Workflow = {
  group: string;
  title: string;
  description: string;
  method: 'GET' | 'POST' | 'PATCH' | 'PUT';
  path: string;
  body: string;
};
export const workflows: Workflow[] = [
  {
    group: 'Build',
    title: 'Venues',
    description: 'Create venues and inspect operational inventory.',
    method: 'POST',
    path: '/api/v1/admin/venues',
    body: '{"name":"Harbour Arena","timezone_name":"Africa/Lagos"}',
  },
  {
    group: 'Build',
    title: 'Venue layouts',
    description: 'Version, edit and publish floor plans.',
    method: 'POST',
    path: '/api/v1/admin/venues/{venue_id}/layout-versions',
    body: '{"name":"Main bowl v1"}',
  },
  {
    group: 'Build',
    title: 'Events',
    description: 'Create events and control their lifecycle.',
    method: 'POST',
    path: '/api/v1/admin/events',
    body: '{"venue_id":"ven_…","name":"Saturday Live","admission_policy":"SINGLE_ENTRY"}',
  },
  {
    group: 'Commerce',
    title: 'Pricing',
    description: 'Define tiers and assign commercial terms.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/price-tiers',
    body: '{"code":"STANDARD","name":"Standard","amount_minor":250000,"currency":"NGN"}',
  },
  {
    group: 'Commerce',
    title: 'Inventory',
    description: 'Materialize the published layout into event inventory.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/materialize-layout',
    body: '{}',
  },
  {
    group: 'Commerce',
    title: 'Blocks',
    description: 'Protect operational inventory and release safely.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/blocks',
    body: '{"purpose":"PRODUCTION","reason":"Sightline hold","reserved_unit_ids":[]}',
  },
  {
    group: 'Commerce',
    title: 'Allocations',
    description: 'Assign neutral channel or non-public inventory.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/allocations',
    body: '{"mode":"CHANNEL","partner_id":"ptr_…","purpose":"CHANNEL","release_destination":{"kind":"SHARED"}}',
  },
  {
    group: 'Partners',
    title: 'Partner configuration',
    description: 'Credentials, access, return destinations and webhooks.',
    method: 'PUT',
    path: '/api/v1/admin/partners/{partner_id}/allowed-return-urls',
    body: '{"urls":["https://partner.example/checkout/return"]}',
  },
  {
    group: 'Live event',
    title: 'Sales lifecycle',
    description: 'Open sales only after the event passes its readiness gate.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/open-sales',
    body: '{}',
  },
  {
    group: 'Live event',
    title: 'Pause sales',
    description: 'Stop new acquisition while existing protected transactions resolve.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/pause-sales',
    body: '{}',
  },
  {
    group: 'Live event',
    title: 'Resume sales',
    description: 'Resume acquisition from an explicitly paused event.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/resume-sales',
    body: '{}',
  },
  {
    group: 'Live event',
    title: 'Close sales',
    description: 'Close acquisition without erasing existing commercial history.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/close-sales',
    body: '{}',
  },
  {
    group: 'Live event',
    title: 'Cancel event',
    description: 'Cancel with an explicit auditable operational reason.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/cancel',
    body: '{"reason":"Event cancelled by promoter"}',
  },
  {
    group: 'Live event',
    title: 'Complete event',
    description: 'Mark closed event operations complete while retaining all history.',
    method: 'POST',
    path: '/api/v1/admin/events/{event_id}/complete',
    body: '{}',
  },
  {
    group: 'Live event',
    title: 'Ticket operations',
    description: 'Void, rotate credentials, or explicitly release capacity.',
    method: 'POST',
    path: '/api/v1/admin/tickets/{ticket_id}/void',
    body: '{"reason":"Customer support correction"}',
  },
  {
    group: 'Live event',
    title: 'Admission operations',
    description: 'Supervised overrides and auditable admission reversal.',
    method: 'POST',
    path: '/api/v1/admin/admissions/manual-override',
    body: '{"event_id":"evt_…","ticket_id":"tkt_…","reason":"Accessibility desk verification","supervisor_user_id":"usr_…"}',
  },
  {
    group: 'Operations',
    title: 'Inventory reporting',
    description: 'Reconcile current inventory obligations separately from historical sales.',
    method: 'GET',
    path: '/api/v1/admin/events/{event_id}/reports/inventory',
    body: '',
  },
  {
    group: 'Operations',
    title: 'Commercial reporting',
    description:
      'Inspect immutable Sale facts and current sold capacity without conflating issuance.',
    method: 'GET',
    path: '/api/v1/admin/events/{event_id}/reports/sales',
    body: '',
  },
  {
    group: 'Operations',
    title: 'Admission reporting',
    description: 'Review active and reversed Admissions plus every scan outcome.',
    method: 'GET',
    path: '/api/v1/admin/events/{event_id}/reports/admission',
    body: '',
  },
  {
    group: 'Operations',
    title: 'Audit explorer',
    description: 'Search a bounded, stable page of append-only material state changes.',
    method: 'GET',
    path: '/api/v1/admin/events/{event_id}/audit?limit=50',
    body: '',
  },
  {
    group: 'Operations',
    title: 'Accreditation export',
    description: 'Generate a read-only CSV snapshot without QR credentials or unnecessary PII.',
    method: 'GET',
    path: '/api/v1/admin/events/{event_id}/accreditation-export',
    body: '',
  },
  {
    group: 'Operations',
    title: 'Metrics and alerts',
    description: 'Inspect advisory operational signals derived from authoritative records.',
    method: 'GET',
    path: '/api/v1/admin/events/{event_id}/metrics',
    body: '',
  },
];
